import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const observeSource = await readFile(new URL('./ObserveView.vue', import.meta.url), 'utf8')

test('observe page no longer starts a per-user market decision task', () => {
  assert.doesNotMatch(observeSource, /startSyncJob\(\{ taskType: 'DECISION' \}\)/)
  assert.doesNotMatch(observeSource, /onAutoDecide/)
  assert.match(observeSource, /router\.push\('\/decision'\)/)
})

test('observe empty state explains that market decisions are generated by the system', () => {
  assert.match(observeSource, /等待系统生成市场决策后查看最新结果/)
  assert.match(observeSource, /查看最新决策/)
})
