import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const observeSource = await readFile(new URL('./ObserveView.vue', import.meta.url), 'utf8')

test('observe page no longer starts a per-user market decision task', () => {
  assert.doesNotMatch(observeSource, /startSyncJob\(\{ taskType: 'DECISION' \}\)/)
  assert.doesNotMatch(observeSource, /onAutoDecide/)
  assert.match(observeSource, /router\.push\('\/decision'\)/)
})

test('observe empty state explains that market decisions are generated by the system', () => {
  assert.match(observeSource, /等待系统生成市场决策后查看最新结果/)
  assert.match(observeSource, /查看最新决策/)
})

test('observe research cards keep analysis text selectable for planning and review', () => {
  assert.match(observeSource, /class="page observe-page"/)
  assert.match(observeSource, /\.observe-page \.card\s*\{[\s\S]*?user-select:\s*text;/)
  assert.doesNotMatch(observeSource, /\.page\s*\{[\s\S]*?user-select:\s*none;/)
})

test('observe filtering visibly confirms card changes without ignoring reduced-motion preferences', () => {
  assert.match(observeSource, /<TransitionGroup v-else name="observe-card" tag="div" class="cards">/)
  assert.match(observeSource, /\.observe-card-enter-active,[\s\S]*?transition:\s*opacity 160ms ease, transform 180ms ease;/)
  assert.match(observeSource, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.observe-card-enter-active,[\s\S]*?transition:\s*none;/)
})

test('mobile observe actions keep frequent controls compact and touch-friendly', () => {
  assert.match(
    observeSource,
    /@media \(max-width: 560px\)[\s\S]*?\.page \.header > \.actions\s*\{[\s\S]*?display:\s*flex;[\s\S]*?width:\s*auto;[\s\S]*?max-width:\s*100%;/,
  )
  assert.match(observeSource, /\.page \.header > \.actions \.btn\s*\{[\s\S]*?min-height:\s*42px;/)
})
