USE apex;

CREATE TABLE IF NOT EXISTS stock_fin_indicator (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(16) NOT NULL,
    report_date DATE NOT NULL,
    eps DECIMAL(18, 6) NULL,
    eps_weighted DECIMAL(18, 6) NULL,
    eps_adjusted DECIMAL(18, 6) NULL,
    eps_excl DECIMAL(18, 6) NULL,
    bps DECIMAL(18, 6) NULL,
    ocfps DECIMAL(18, 6) NULL,
    capital_reserve_ps DECIMAL(18, 6) NULL,
    undistributed_ps DECIMAL(18, 6) NULL,
    roe DECIMAL(18, 6) NULL,
    roa DECIMAL(18, 6) NULL,
    gross_margin DECIMAL(18, 6) NULL,
    net_margin DECIMAL(18, 6) NULL,
    operate_margin DECIMAL(18, 6) NULL,
    debt_ratio DECIMAL(18, 6) NULL,
    current_ratio DECIMAL(18, 6) NULL,
    quick_ratio DECIMAL(18, 6) NULL,
    payload JSON NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'akshare',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fin_indicator_code_date (code, report_date),
    KEY idx_fin_indicator_date (report_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_fin_abstract (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(16) NOT NULL,
    report_date DATE NOT NULL,
    net_profit DECIMAL(24, 4) NULL,
    net_profit_yoy DECIMAL(18, 6) NULL,
    net_profit_excl DECIMAL(24, 4) NULL,
    net_profit_excl_yoy DECIMAL(18, 6) NULL,
    revenue DECIMAL(24, 4) NULL,
    revenue_yoy DECIMAL(18, 6) NULL,
    eps_basic DECIMAL(18, 6) NULL,
    bps DECIMAL(18, 6) NULL,
    ocfps DECIMAL(18, 6) NULL,
    net_margin DECIMAL(18, 6) NULL,
    roe DECIMAL(18, 6) NULL,
    debt_ratio DECIMAL(18, 6) NULL,
    current_ratio DECIMAL(18, 6) NULL,
    quick_ratio DECIMAL(18, 6) NULL,
    payload JSON NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'akshare-ths',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fin_abstract_code_date (code, report_date),
    KEY idx_fin_abstract_date (report_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_fin_report_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(16) NOT NULL,
    statement_type VARCHAR(16) NOT NULL,
    report_date DATE NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    item_value DECIMAL(24, 4) NULL,
    item_value_text VARCHAR(64) NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'akshare-sina',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fin_report_item (code, statement_type, report_date, item_name),
    KEY idx_fin_report_code_type_date (code, statement_type, report_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
