USE apex;

CREATE TABLE IF NOT EXISTS stock_company_profile (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(16) NOT NULL,
    org_name VARCHAR(256) NULL,
    org_name_en VARCHAR(512) NULL,
    former_name VARCHAR(1024) NULL,
    a_code VARCHAR(16) NULL,
    a_name VARCHAR(64) NULL,
    region VARCHAR(64) NULL,
    area_board VARCHAR(64) NULL,
    industry_em VARCHAR(256) NULL,
    industry_csrc VARCHAR(256) NULL,
    board_path VARCHAR(256) NULL,
    concepts VARCHAR(2048) NULL,
    chairman VARCHAR(64) NULL,
    legal_person VARCHAR(64) NULL,
    president VARCHAR(64) NULL,
    secretary VARCHAR(64) NULL,
    control_holder VARCHAR(256) NULL,
    control_ratio VARCHAR(64) NULL,
    real_controller VARCHAR(256) NULL,
    real_controller_ratio VARCHAR(128) NULL,
    org_form VARCHAR(64) NULL,
    found_date DATE NULL,
    list_date DATE NULL,
    reg_capital DECIMAL(20, 4) NULL,
    issue_price DECIMAL(16, 4) NULL,
    employee_num INT NULL,
    manager_num INT NULL,
    main_business VARCHAR(1024) NULL,
    org_profile TEXT NULL,
    org_highlight VARCHAR(1024) NULL,
    business_scope TEXT NULL,
    website VARCHAR(256) NULL,
    email VARCHAR(256) NULL,
    phone VARCHAR(128) NULL,
    fax VARCHAR(128) NULL,
    office_address VARCHAR(512) NULL,
    reg_address VARCHAR(512) NULL,
    reg_num VARCHAR(64) NULL,
    trade_market VARCHAR(64) NULL,
    payload JSON NULL,
    source VARCHAR(32) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_company_profile_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
