USE apex;

CREATE TABLE IF NOT EXISTS decision_run (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    run_no VARCHAR(64) NOT NULL COMMENT '运行编号',
    action_date DATE NOT NULL COMMENT '决策交易日',
    as_of_time DATETIME NOT NULL COMMENT '数据可见截止时间',
    group_name VARCHAR(64) NULL COMMENT '决策分组',
    mode VARCHAR(16) NOT NULL DEFAULT 'LIVE' COMMENT 'LIVE/REPLAY/SHADOW',
    rule_version VARCHAR(64) NULL COMMENT '规则版本',
    model_version VARCHAR(64) NULL COMMENT '模型版本',
    feature_version VARCHAR(64) NULL COMMENT '特征版本',
    data_level VARCHAR(16) NULL COMMENT '数据质量等级',
    data_cutoff_json MEDIUMTEXT NULL COMMENT '各数据源截止时间JSON',
    config_snapshot_json MEDIUMTEXT NULL COMMENT '配置快照JSON',
    status VARCHAR(16) NOT NULL COMMENT 'RUNNING/SUCCESS/FAILED/PUBLISHED',
    message VARCHAR(512) NULL COMMENT '运行消息',
    started_at DATETIME NOT NULL COMMENT '开始时间',
    finished_at DATETIME NULL COMMENT '结束时间',
    published TINYINT NOT NULL DEFAULT 0 COMMENT '是否发布',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_decision_run_no (run_no),
    KEY idx_decision_run_date (action_date),
    KEY idx_decision_run_publish (action_date, published, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能决策运行';

CREATE TABLE IF NOT EXISTS decision_feature_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    run_id BIGINT NOT NULL COMMENT '决策运行ID',
    code VARCHAR(16) NOT NULL COMMENT '证券代码',
    action VARCHAR(16) NULL COMMENT 'BUY/SELL/HOLD/AVOID',
    feature_version VARCHAR(64) NOT NULL COMMENT '特征版本',
    feature_hash VARCHAR(64) NOT NULL COMMENT '特征SHA-256',
    signal_score DECIMAL(10, 4) NULL COMMENT '策略信号分',
    confluence_count INT NULL COMMENT '共振策略数',
    hot_source_count INT NULL COMMENT '热点来源数',
    mainline_match TINYINT NULL COMMENT '是否匹配主线',
    valuation_level VARCHAR(32) NULL COMMENT '估值档位',
    market_stance VARCHAR(16) NULL COMMENT '市场状态',
    data_quality VARCHAR(16) NULL COMMENT '特征数据质量',
    feature_json MEDIUMTEXT NOT NULL COMMENT '完整特征JSON',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_decision_feature_run_code_action (run_id, code, action),
    KEY idx_decision_feature_code (code),
    KEY idx_decision_feature_hash (feature_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能决策特征快照';

CREATE TABLE IF NOT EXISTS decision_outcome (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    action_id BIGINT NOT NULL COMMENT '操作清单ID',
    run_id BIGINT NULL COMMENT '决策运行ID',
    code VARCHAR(16) NOT NULL COMMENT '证券代码',
    action_date DATE NOT NULL COMMENT '决策交易日',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/PARTIAL/COMPLETE/INVALID',
    return_1d DECIMAL(12, 6) NULL COMMENT '1交易日收益率',
    return_3d DECIMAL(12, 6) NULL COMMENT '3交易日收益率',
    return_5d DECIMAL(12, 6) NULL COMMENT '5交易日收益率',
    return_10d DECIMAL(12, 6) NULL COMMENT '10交易日收益率',
    return_20d DECIMAL(12, 6) NULL COMMENT '20交易日收益率',
    excess_1d DECIMAL(12, 6) NULL COMMENT '1交易日超额收益率',
    excess_3d DECIMAL(12, 6) NULL COMMENT '3交易日超额收益率',
    excess_5d DECIMAL(12, 6) NULL COMMENT '5交易日超额收益率',
    excess_10d DECIMAL(12, 6) NULL COMMENT '10交易日超额收益率',
    excess_20d DECIMAL(12, 6) NULL COMMENT '20交易日超额收益率',
    mfe DECIMAL(12, 6) NULL COMMENT '最大有利变动',
    mae DECIMAL(12, 6) NULL COMMENT '最大不利变动',
    stop_hit TINYINT NULL COMMENT '是否触及止损',
    stop_hit_date DATE NULL COMMENT '首次止损日期',
    target_hit TINYINT NULL COMMENT '是否触及止盈',
    target_hit_date DATE NULL COMMENT '首次止盈日期',
    net_return DECIMAL(12, 6) NULL COMMENT '成本后理论收益率',
    adoption_status VARCHAR(16) NULL COMMENT '采纳状态',
    actual_price DECIMAL(16, 4) NULL COMMENT '实际成交价',
    actual_weight DECIMAL(10, 4) NULL COMMENT '实际仓位',
    slippage DECIMAL(12, 6) NULL COMMENT '成交滑点',
    actual_pnl DECIMAL(18, 2) NULL COMMENT '实际盈亏',
    quality_status VARCHAR(32) NULL COMMENT '结果质量状态',
    calculated_at DATETIME NULL COMMENT '最后计算时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_decision_outcome_action (action_id),
    KEY idx_decision_outcome_run_code (run_id, code),
    KEY idx_decision_outcome_date (action_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能决策结果归因';

ALTER TABLE daily_action
    ADD COLUMN run_id BIGINT NULL COMMENT '决策运行ID',
    ADD COLUMN rank_no INT NULL COMMENT '运行内排序',
    ADD COLUMN confidence DECIMAL(10, 4) NULL COMMENT '决策置信度',
    ADD COLUMN uncertainty DECIMAL(10, 4) NULL COMMENT '决策不确定性',
    ADD COLUMN decision_status VARCHAR(16) NULL COMMENT '决策状态';
