/** 金融通识、市场机制、宏观、估值、行为与公司金融词条。 */
export const FINANCE_TERMS = [
  // —— 基础 ——
  {
    id: 'money',
    title: '货币',
    aliases: ['Money', '通货'],
    category: '基础',
    short: '被普遍接受的支付、计价和储藏价值工具。',
    plain: '货币让人们不用以物易物，也让不同商品可以用同一把尺子标价。',
    detail: '货币通常承担交易媒介、价值尺度和价值储藏三项功能。现金只是货币的一部分，银行存款等也可参与支付。货币能否稳定履行这些功能，取决于信用、供给与购买力。',
    highlights: ['同一把尺子标价'],
    related: ['money_supply', 'credit', 'inflation'],
  },
  {
    id: 'credit',
    title: '信用',
    aliases: ['Credit', '信用关系'],
    category: '基础',
    short: '基于未来偿付承诺形成的借贷与交易关系。',
    plain: '信用就是今天先拿到钱或商品，靠未来按约定偿还来完成交换。',
    detail: '信用把储蓄转化为投资，也会形成债权和债务。借款人的偿付能力、意愿、抵押物和宏观环境共同决定信用风险与融资价格；信用扩张过快还可能累积杠杆风险。',
    highlights: ['未来按约定偿还'],
    related: ['interest_rate', 'bond', 'credit_spread'],
  },
  {
    id: 'interest_rate',
    title: '利率',
    aliases: ['Interest Rate', '利息率'],
    category: '基础',
    short: '资金在一定期限内的使用价格。',
    plain: '借钱要付的价格就是利率；期限、信用和通胀预期都会影响它。',
    detail: '利率通常表示为本金的年化百分比。央行政策、资金供求、期限和违约风险都会改变利率。利率上升通常压低既有债券价格，并提高企业融资成本和估值折现率。',
    highlights: ['借钱要付的价格'],
    related: ['policy_rate', 'real_interest_rate', 'bond'],
  },
  {
    id: 'exchange_rate',
    title: '汇率',
    aliases: ['Exchange Rate', '外汇牌价'],
    category: '基础',
    short: '一种货币兑换另一种货币的比价。',
    plain: '汇率告诉你一单位本币能换多少外币，升贬值会改变进口、出口和海外资产回报。',
    detail: '汇率受利差、通胀、贸易与资本流动、政策预期等影响。分析时先确认直接或间接标价法；同样写“汇率上涨”，在不同标价下可能对应本币升值或贬值。',
    highlights: ['改变进口、出口和海外资产回报'],
    related: ['trade_balance', 'interest_rate', 'inflation'],
  },
  {
    id: 'inflation',
    title: '通胀',
    aliases: ['通货膨胀', 'Inflation'],
    category: '基础',
    short: '总体价格水平持续上涨、货币购买力下降。',
    plain: '同样一笔钱以后买到的东西更少，就是购买力被通胀侵蚀。',
    detail: '通胀不是少数商品一次涨价，而是广泛且持续的价格上升。适度通胀常伴随需求增长，过高通胀会压缩实际收入并促使货币政策收紧；通缩则是总体价格持续下降。',
    highlights: ['购买力被通胀侵蚀'],
    related: ['cpi', 'real_interest_rate', 'stagflation'],
  },
  {
    id: 'asset',
    title: '资产',
    aliases: ['Assets', '会计资产'],
    category: '基础',
    short: '由过去事项形成、预期能带来经济利益的资源。',
    plain: '资产不是“值钱的东西”这么简单，关键是企业能控制并可能从中获得未来收益。',
    detail: '资产包括现金、应收、存货、设备、投资等，可分为流动和非流动资产。账面价值不等于市场价值；分析资产质量还要看变现能力、减值风险和真实盈利贡献。',
    highlights: ['能控制', '未来收益'],
    related: ['liability', 'owners_equity', 'balance_sheet'],
  },
  {
    id: 'liability',
    title: '负债',
    aliases: ['Liabilities', '会计负债'],
    category: '基础',
    short: '由过去事项形成、预期需要偿付的现时义务。',
    plain: '负债是企业未来要交付现金、商品或服务的责任，不只包括银行借款。',
    detail: '负债包括应付账款、借款、债券和合同负债等，可分为流动和非流动负债。分析时要看期限、利率、币种和是否有息，短债集中到期可能造成流动性压力。',
    highlights: ['未来要交付', '不只包括银行借款'],
    related: ['asset', 'owners_equity', 'debt_ratio'],
  },
  {
    id: 'owners_equity',
    title: '所有者权益',
    aliases: ['权益', '股东权益', '净资产', 'Owners Equity'],
    category: '基础',
    short: '资产扣除负债后归属于所有者的剩余权益。',
    plain: '把公司所有资产变现并还清负债，理论上剩下的部分才属于股东。',
    detail: '基本会计恒等式为资产=负债+所有者权益。权益通常包括股本、资本公积、盈余公积和未分配利润；它是账面概念，与股票市值并不相同。',
    highlights: ['还清负债', '剩下的部分'],
    related: ['asset', 'liability', 'roe'],
  },
  {
    id: 'accounting_income',
    title: '收入',
    aliases: ['会计收入', 'Income'],
    category: '基础',
    short: '企业日常活动形成、导致权益增加的经济利益流入。',
    plain: '收入表示业务做了多大，但确认收入不等于现金已经到账。',
    detail: '会计收入需满足确认条件，并按履约进度或控制权转移确认。营业收入是上市公司最常见口径；分析时要结合应收账款、合同负债和经营现金流判断收入质量。',
    highlights: ['不等于现金已经到账'],
    related: ['revenue', 'expense', 'accounts_receivable'],
  },
  {
    id: 'expense',
    title: '费用',
    aliases: ['Expenses', '期间费用'],
    category: '基础',
    short: '企业日常活动中导致权益减少的经济利益流出。',
    plain: '费用是为了取得收入而消耗的资源，但付现金和确认费用可能不在同一时间。',
    detail: '常见期间费用包括销售、管理、研发和财务费用。成本与费用都影响利润，但归集对象和报表位置不同；折旧等费用即使当期不支付现金，也会减少会计利润。',
    highlights: ['付现金和确认费用可能不在同一时间'],
    related: ['accounting_income', 'profit', 'income_statement'],
  },
  {
    id: 'profit',
    title: '利润',
    aliases: ['Profit', '会计利润'],
    category: '基础',
    short: '一定期间收入扣除成本费用及相关损益后的经营成果。',
    plain: '利润是会计口径的“赚了多少”，不等于账户里实际多了多少现金。',
    detail: '利润表会逐层形成毛利润、营业利润、利润总额和净利润。判断利润质量要看是否来自主营、是否可持续，以及能否转化为经营现金流。',
    highlights: ['不等于账户里实际多了多少现金'],
    related: ['net_profit', 'operating_cash_flow', 'income_statement'],
  },
  {
    id: 'time_value_money',
    title: '货币时间价值',
    aliases: ['Time Value of Money', 'TVM'],
    category: '基础',
    short: '同额资金在不同时间点的经济价值不同。',
    plain: '今天的一百元通常比一年后的一百元更值钱，因为今天可以投资并承担更少不确定性。',
    detail: '现值与终值通过利率连接。投资估值要把不同时间的现金流折到同一时点比较；折现率越高，远期现金流的现值越低。',
    highlights: ['今天的一百元', '更值钱'],
    related: ['compound_interest', 'npv', 'dcf'],
  },
  {
    id: 'compound_interest',
    title: '复利',
    aliases: ['Compound Interest', '利滚利'],
    category: '基础',
    short: '每期收益加入本金，后续收益继续在累计本金上计算。',
    plain: '赚到的收益也继续参与赚钱，时间越长，复利效应越明显。',
    detail: '复利终值取决于本金、收益率、计息频率和期限。复利也会放大负收益与高成本，短期收益率外推长期时还要警惕波动顺序和不可持续假设。',
    highlights: ['收益也继续参与赚钱'],
    related: ['time_value_money', 'annualized_return', 'interest_rate'],
  },
  {
    id: 'money_supply',
    title: '货币供应量',
    aliases: ['M0', 'M1', 'M2', 'Money Supply'],
    category: '基础',
    short: '经济中可用于支付和储藏价值的货币总量。',
    plain: 'M0、M1、M2像不同口径的水位尺，范围从现金逐步扩大到更多存款。',
    detail: 'M0通常指流通中现金，M1在此基础上加入活期存款，M2再纳入定期等更广义存款。各经济体统计口径不同，货币增速需结合信用、通胀和经济活动解读。',
    highlights: ['不同口径的水位尺'],
    related: ['money', 'monetary_policy', 'inflation'],
  },
  {
    id: 'real_interest_rate',
    title: '实际利率',
    aliases: ['Real Interest Rate', '真实利率'],
    category: '基础',
    short: '名义利率扣除通胀影响后的资金实际回报。',
    plain: '存款利率高于通胀，购买力才可能真正增加。',
    detail: '近似关系为实际利率≈名义利率−预期通胀率。实际利率上升会提高持有现金与债券的吸引力，并通常压低远期资产估值；分析投资决策时预期通胀往往比已公布通胀更重要。',
    highlights: ['购买力才可能真正增加'],
    related: ['interest_rate', 'inflation', 'policy_rate'],
  },

  // —— 市场 ——
  {
    id: 'stock',
    title: '股票',
    aliases: ['Stock', '股份'],
    category: '市场',
    short: '代表对公司部分所有权及相应收益、表决权的证券。',
    plain: '买股票是在买公司的一小部分，回报来自公司成长、分红和市场重新定价。',
    detail: '普通股股东通常享有剩余收益权和表决权，但清偿顺序排在债权人之后。股价会受公司经营、行业、利率、风险偏好和流动性共同影响。',
    highlights: ['买公司的一小部分'],
    related: ['bond', 'owners_equity', 'secondary_market'],
  },
  {
    id: 'bond',
    title: '债券',
    aliases: ['Bond', '固定收益证券'],
    category: '市场',
    short: '发行人承诺按约定付息并偿还本金的债务证券。',
    plain: '买债券更像把钱借给发行人，主要关心能否按时付息还本。',
    detail: '债券价格与市场利率通常反向变动。分析债券还要看期限、票息、信用等级、偿付顺序和流动性；“固定收益”不代表价格不波动或一定没有损失。',
    highlights: ['把钱借给发行人'],
    related: ['interest_rate', 'credit_spread', 'yield_curve'],
  },
  {
    id: 'fund',
    title: '基金',
    aliases: ['Fund', '投资基金'],
    category: '市场',
    short: '汇集投资者资金，按既定目标进行组合投资的载体。',
    plain: '基金把许多人的钱集中起来，由规则或管理人买一篮子资产。',
    detail: '基金可按开放方式、资产类别和管理方式分类。收益归投资者、风险也由投资者承担；选择时要看策略、持仓、费用、跟踪误差、流动性和管理人稳定性。',
    highlights: ['买一篮子资产'],
    related: ['etf', 'stock', 'bond'],
  },
  {
    id: 'etf',
    title: 'ETF',
    aliases: ['交易型开放式基金', 'Exchange Traded Fund'],
    category: '市场',
    short: '可在交易所买卖、通常跟踪一篮子资产的基金。',
    plain: 'ETF既像基金分散持仓，又能像股票一样在盘中交易。',
    detail: '多数ETF跟踪指数，也有主动型和商品型产品。交易价格可能短暂偏离基金净值，投资者还需关注费率、规模、成交活跃度、跟踪误差和申赎机制。',
    highlights: ['像股票一样在盘中交易'],
    related: ['fund', 'market_index', 'market_liquidity'],
  },
  {
    id: 'index_fund',
    title: '指数基金',
    aliases: ['Index Fund', '被动指数基金'],
    category: '市场',
    short: '以复制某个指数表现为主要目标的基金。',
    plain: '指数基金可做成ETF或场外基金；ETF也可能采用主动策略，两者不能画等号。',
    detail: '指数基金按规则跟踪指数，可采用ETF或普通场外开放式基金形式；ETF强调可在交易所交易，并不必然跟踪指数。选择时应看投资策略、费率、跟踪误差、申赎安排和流动性。',
    highlights: ['ETF也可能采用主动策略', '不能画等号'],
    related: ['fund', 'etf', 'market_index'],
  },
  {
    id: 'derivative',
    title: '衍生品',
    aliases: ['金融衍生品', 'Derivative'],
    category: '市场',
    short: '价值取决于某项基础资产、利率、汇率或指数的合约。',
    plain: '衍生品本身的价值跟着另一个标的变化，可用于对冲，也能放大风险。',
    detail: '常见衍生品包括远期、期货、期权和互换。它们可转移价格风险、提高资金效率，也会带来杠杆、保证金、交易对手和模型风险。',
    highlights: ['可用于对冲', '放大风险'],
    related: ['forward_contract', 'futures', 'option'],
  },
  {
    id: 'forward_contract',
    title: '远期合约',
    aliases: ['远期', 'Forward Contract'],
    category: '市场',
    short: '双方约定未来以确定价格买卖标的的场外合约。',
    plain: '今天先把未来成交的价格约好，到期再按约定交割。',
    detail: '远期条款可定制，但通常在场外交易，存在交易对手违约风险。它与期货经济功能相近，期货则更标准化并通过保证金和每日结算降低信用风险。',
    highlights: ['未来成交的价格约好'],
    related: ['futures', 'swap', 'hedging'],
  },
  {
    id: 'futures',
    title: '期货',
    aliases: ['Futures', '期货合约'],
    category: '市场',
    short: '在交易所交易、约定未来买卖标的的标准化合约。',
    plain: '期货只需缴纳一部分保证金就能管理较大名义金额，因此盈亏会被放大。',
    detail: '期货采用保证金和每日无负债结算，可能触发追加保证金。多数投资者在到期前平仓，也有现金或实物交割；套期保值仍存在基差风险。',
    highlights: ['盈亏会被放大'],
    related: ['margin', 'leverage', 'forward_contract'],
  },
  {
    id: 'option',
    title: '期权',
    aliases: ['Options', '选择权'],
    category: '市场',
    short: '买方有权但无义务在约定条件下买入或卖出标的的合约。',
    plain: '期权买方付出权利金换取选择权，卖方收取权利金并承担履约义务。',
    detail: '期权分看涨与看跌，价值受标的价格、行权价、剩余期限、波动率和利率影响。买方最大损失通常限于权利金，卖方风险可能很大，不能只看胜率。',
    highlights: ['有权但无义务', '承担履约义务'],
    related: ['call_option', 'put_option', 'option_time_value'],
  },
  {
    id: 'swap',
    title: '互换',
    aliases: ['掉期', 'Swap'],
    category: '市场',
    short: '双方按约定规则交换未来现金流的场外合约。',
    plain: '互换不是交换资产所有权，而是交换一串利息、汇率等现金流。',
    detail: '常见有利率互换和货币互换。互换可调整融资结构或对冲风险，但期限通常较长，涉及交易对手信用、抵押品和提前终止价值。',
    highlights: ['交换一串', '现金流'],
    related: ['interest_rate', 'exchange_rate', 'derivative'],
  },
  {
    id: 'primary_market',
    title: '一级市场',
    aliases: ['一级发行', '证券发行', 'Primary Market'],
    category: '市场',
    short: '发行人首次或再次向投资者发行证券、募集资金的市场。',
    plain: '一级市场的钱直接进入发行人，核心是“新证券怎么卖出去”。',
    detail: '股票IPO、增发和债券发行都属于一级市场活动，通常由承销机构协助定价与销售。发行完成后，证券才主要在二级市场投资者之间流转。',
    highlights: ['直接进入发行人'],
    related: ['ipo', 'underwriting', 'secondary_market'],
  },
  {
    id: 'secondary_market',
    title: '二级市场',
    aliases: ['二级交易', '流通市场', 'Secondary Market'],
    category: '市场',
    short: '已发行证券在投资者之间转让和交易的市场。',
    plain: '二级市场多数交易只是投资者换手，资金通常不会直接进入上市公司。',
    detail: '二级市场提供价格发现和流动性，也会影响发行人后续融资成本。交易所市场规则标准化，场外市场则由交易商或做市商组织报价。',
    highlights: ['投资者换手', '不会直接进入上市公司'],
    related: ['primary_market', 'market_maker', 'market_liquidity'],
  },
  {
    id: 'ipo',
    title: 'IPO',
    aliases: ['首次公开发行', 'Initial Public Offering'],
    category: '市场',
    short: '公司首次向公众发行股票并申请上市。',
    plain: 'IPO让私人公司第一次向公众股东募资，并接受公开市场的信息披露约束。',
    detail: 'IPO通常包括辅导、审核或注册、询价定价、发行和上市。发行价不代表内在价值，上市后还可能受流通盘、锁定期和市场情绪影响。',
    highlights: ['第一次向公众股东募资'],
    related: ['primary_market', 'underwriting', 'lockup_expiry'],
  },
  {
    id: 'underwriting',
    title: '承销',
    aliases: ['证券承销', 'Underwriting'],
    category: '市场',
    short: '中介机构协助发行人定价、销售证券并承担约定责任。',
    plain: '承销商连接发行人与投资者，帮助新证券完成定价和销售。',
    detail: '承销可分包销、余额包销或代销等安排，风险承担不同。承销并不等于为证券未来表现担保，投资者仍需独立判断发行人质量和定价。',
    highlights: ['连接发行人与投资者'],
    related: ['ipo', 'primary_market', 'bond'],
  },
  {
    id: 'market_maker',
    title: '做市商',
    aliases: ['Market Maker', '做市'],
    category: '市场',
    short: '持续提供买卖报价并承担一定库存风险的交易机构。',
    plain: '做市商同时报出愿意买和愿意卖的价格，让其他人更容易成交。',
    detail: '做市商主要从买卖价差和流动性服务中获取收益，同时管理库存、价格和对手方风险。做市能改善流动性，但不保证任何时刻都有无限深度。',
    highlights: ['同时报出', '更容易成交'],
    related: ['market_liquidity', 'order_book', 'secondary_market'],
  },
  {
    id: 'market_liquidity',
    title: '流动性',
    aliases: ['市场流动性', 'Liquidity'],
    category: '市场',
    short: '资产能否快速、低成本地按接近公允价格成交。',
    plain: '流动性好意味着想买卖时容易找到对手方，而且不必大幅让价。',
    detail: '流动性可从成交量、买卖价差、盘口深度和价格冲击观察。流动性会随市场状态变化，压力时期常迅速收缩；流动性好也不等于价格不会下跌。',
    highlights: ['不必大幅让价'],
    related: ['liquidity_risk', 'market_maker', 'order_book'],
  },
  {
    id: 'arbitrage',
    title: '套利',
    aliases: ['Arbitrage', '无风险套利'],
    category: '市场',
    short: '利用相关资产或市场间的不一致定价构造低风险收益。',
    plain: '套利是在价格关系暂时失衡时同时买低卖高，但现实中仍有执行和模型风险。',
    detail: '严格无风险套利要求初始净投入不为正且未来不会亏损，现实策略多为统计套利，仍会受价差继续扩大、交易成本、融券和流动性限制。',
    highlights: ['同时买低卖高', '仍有执行和模型风险'],
    related: ['apt', 'mean_reversion', 'hedging'],
  },
  {
    id: 'margin',
    title: '保证金',
    aliases: ['Margin', '交易保证金'],
    category: '市场',
    short: '为履约和覆盖潜在损失而缴纳或冻结的资金。',
    plain: '保证金不是买下全部资产的钱，而是为较大名义头寸提供履约担保。',
    detail: '期货和部分衍生品按风险收取初始及维持保证金。亏损使账户权益低于要求时可能追加保证金或被强平，保证金比例越低，隐含杠杆通常越高。',
    highlights: ['履约担保'],
    related: ['futures', 'leverage', 'stop_loss'],
  },
  {
    id: 'leverage',
    title: '杠杆',
    aliases: ['Leverage', '财务杠杆', '交易杠杆'],
    category: '市场',
    short: '用借款或衍生品放大资金对资产敞口的机制。',
    plain: '杠杆会同时放大盈利和亏损，方向判断正确也可能因波动先被强平。',
    detail: '杠杆可来自负债融资、保证金交易或衍生品。评估杠杆不能只看倍数，还要看波动、融资成本、追保规则和最坏情景下是否有足够现金。',
    highlights: ['同时放大盈利和亏损'],
    related: ['margin', 'debt_ratio', 'position_ratio'],
  },
  {
    id: 'long_position',
    title: '做多',
    aliases: ['多头', 'Long'],
    category: '市场',
    short: '建立价格上涨时受益的头寸。',
    plain: '做多就是判断价格会上涨，先买入或建立正向敞口。',
    detail: '现货买入、买入看涨期权或买入期货都可能形成多头敞口，但最大损失、资金占用和到期结构不同。方向相同不代表风险结构相同。',
    highlights: ['价格会上涨'],
    related: ['short_selling', 'call_option', 'position_ratio'],
  },
  {
    id: 'short_selling',
    title: '做空',
    aliases: ['空头', '卖空', 'Short Selling'],
    category: '市场',
    short: '建立价格下跌时受益的头寸。',
    plain: '做空通常先借入并卖出，等价格下跌后买回归还；上涨会造成损失。',
    detail: '卖空受融券可得性、费用、保证金和强平规则限制，理论亏损上限高于普通现货做多。期货和期权也能形成空头敞口，但风险形态各不相同。',
    highlights: ['价格下跌后买回归还'],
    related: ['long_position', 'put_option', 'margin_trading'],
  },
  {
    id: 'call_option',
    title: '看涨期权',
    aliases: ['认购期权', 'Call Option'],
    category: '市场',
    short: '赋予买方按约定价格买入标的权利的期权。',
    plain: '看涨期权像为未来上涨保留一个买入价，买方最多通常损失权利金。',
    detail: '标的价格超过行权价越多，看涨期权通常越有价值。到期前还受时间和隐含波动率影响；卖出裸看涨的潜在损失可能很大。',
    highlights: ['未来上涨保留一个买入价'],
    related: ['option', 'put_option', 'delta'],
  },
  {
    id: 'put_option',
    title: '看跌期权',
    aliases: ['认沽期权', 'Put Option'],
    category: '市场',
    short: '赋予买方按约定价格卖出标的权利的期权。',
    plain: '看跌期权像给资产买价格保险，标的大跌时能提供保护。',
    detail: '标的价格低于行权价越多，看跌期权通常越有价值。保护性看跌可限制组合下行风险，但权利金会持续形成成本。',
    highlights: ['给资产买价格保险'],
    related: ['option', 'call_option', 'hedging'],
  },
  {
    id: 'option_intrinsic_value',
    title: '期权内在价值',
    aliases: ['Option Intrinsic Value'],
    category: '市场',
    short: '期权立即行权能够获得的非负经济价值。',
    plain: '假设现在就行权，能赚到的那部分就是内在价值，不能为负。',
    detail: '看涨期权内在价值为max(标的价−行权价,0)，看跌则相反。期权市场价格超过内在价值的部分通常称为时间价值。',
    highlights: ['现在就行权'],
    related: ['option_time_value', 'call_option', 'put_option'],
  },
  {
    id: 'option_time_value',
    title: '期权时间价值',
    aliases: ['时间价值', 'Time Value'],
    category: '市场',
    short: '期权价格扣除内在价值后，对未来可能性的定价。',
    plain: '离到期越久，发生有利行情的机会通常越多，因此期权往往更贵。',
    detail: '时间价值受剩余期限、隐含波动率、利率和分红影响，并通常随到期临近而衰减。临近到期时衰减可能加快，对买方不利、对卖方有利。',
    highlights: ['发生有利行情的机会'],
    related: ['option_intrinsic_value', 'theta', 'volatility'],
  },
  {
    id: 'delta',
    title: 'Delta',
    aliases: ['德尔塔', '期权Delta'],
    category: '市场',
    short: '期权价格对标的价格小幅变化的敏感度。',
    plain: 'Delta近似表示标的变动一元时，期权价格会变多少。',
    detail: '看涨Delta通常在0到1之间，看跌通常在-1到0之间。Delta会随价格、时间和波动率变化，因此Delta对冲需要动态调整。',
    highlights: ['期权价格会变多少'],
    related: ['gamma', 'hedging', 'option'],
  },
  {
    id: 'gamma',
    title: 'Gamma',
    aliases: ['伽马', '期权Gamma'],
    category: '市场',
    short: 'Delta对标的价格变化的敏感度。',
    plain: 'Gamma衡量Delta变得有多快，越高就越需要频繁调整对冲。',
    detail: '平值且临近到期的期权Gamma往往较高。多头期权通常为正Gamma，能从大幅波动受益；空头期权为负Gamma，价格跳动会使风险快速恶化。',
    highlights: ['Delta变得有多快'],
    related: ['delta', 'theta', 'option'],
  },
  {
    id: 'theta',
    title: 'Theta',
    aliases: ['西塔', '期权Theta'],
    category: '市场',
    short: '其他条件不变时，时间流逝对期权价格的影响。',
    plain: 'Theta常被称为时间损耗：越接近到期，买方持有的时间价值越容易减少。',
    detail: '买入期权的Theta通常为负，卖出期权通常为正，但收益并非免费，卖方承担尾部风险。Theta不是固定值，会随价格、期限和波动率改变。',
    highlights: ['时间损耗'],
    related: ['option_time_value', 'gamma', 'vega'],
  },
  {
    id: 'vega',
    title: 'Vega',
    aliases: ['维加', '期权Vega'],
    category: '市场',
    short: '期权价格对隐含波动率变化的敏感度。',
    plain: 'Vega越大，市场对未来波动预期的变化越容易推动期权价格。',
    detail: '期权多头通常为正Vega，隐含波动率上升时受益。Vega在期限较长、接近平值时往往更高；它描述的是模型局部敏感度，不保证实际价格精确变动。',
    highlights: ['未来波动预期'],
    related: ['volatility', 'option', 'theta'],
  },

  // —— 估值与金融理论 ——
  {
    id: 'capm',
    title: '资本资产定价模型',
    aliases: ['资本资产定价', 'CAPM'],
    category: '估值',
    short: '用无风险利率、Beta和市场风险溢价估计资产必要收益率。',
    plain: 'CAPM认为承担更多不能分散掉的市场风险，投资者应要求更高回报。',
    detail: '常见公式为必要收益率=无风险利率+Beta×市场风险溢价。模型便于估计股权成本，但依赖Beta稳定、市场组合可代表等假设，实际应用应做参数敏感性分析。',
    highlights: ['不能分散掉的市场风险'],
    related: ['beta', 'systematic_risk', 'wacc'],
  },
  {
    id: 'apt',
    title: '套利定价理论',
    aliases: ['套利定价', 'APT', 'Arbitrage Pricing Theory'],
    category: '估值',
    short: '用多个系统性因子解释资产预期收益的定价框架。',
    plain: 'APT不像CAPM只盯市场一个因子，而是允许利率、通胀等多个风险来源共同定价。',
    detail: 'APT基于无套利思想，认为资产收益可由多个共同因子及其风险溢价解释。理论不直接指定因子，因子选择、暴露估计和稳定性决定实际效果。',
    highlights: ['多个风险来源共同定价'],
    related: ['capm', 'arbitrage', 'factor_coverage'],
  },
  {
    id: 'efficient_market_hypothesis',
    title: '有效市场假说',
    aliases: ['有效市场', 'EMH', 'Efficient Market Hypothesis'],
    category: '估值',
    short: '资产价格会较快反映相应范围内已知信息的理论。',
    plain: '如果公开信息很快被价格吸收，仅靠大家都知道的消息就很难持续获得超额收益。',
    detail: '弱式、半强式和强式有效对应不同信息集合。有效不等于价格永远正确，也不否认短期偏离，而是强调扣除风险与成本后持续利用公开信息获利很难。',
    highlights: ['很快被价格吸收'],
    related: ['random_walk', 'alpha', 'behavioral_finance'],
  },
  {
    id: 'random_walk',
    title: '随机游走',
    aliases: ['Random Walk', '随机漫步'],
    category: '估值',
    short: '下一期价格变化难以由过去价格变化稳定预测的描述。',
    plain: '如果新信息本身不可预知，价格对新信息的反应也很难提前从旧价格里推出来。',
    detail: '随机游走常与弱式有效市场联系，但不代表价格分布完全随机或没有风险溢价。统计检验还要区分随机游走、独立同分布和更一般的不可预测性。',
    highlights: ['新信息本身不可预知'],
    related: ['efficient_market_hypothesis', 'mean_reversion', 'momentum_factor'],
  },
  {
    id: 'mean_reversion',
    title: '均值回归',
    aliases: ['Mean Reversion', '均值回复'],
    category: '估值',
    short: '变量偏离长期或动态中枢后倾向向中枢靠拢的现象。',
    plain: '价格偏得很远后可能回到常态，但真正的中枢也可能已经改变。',
    detail: '均值回归可用于价差、估值和波动率研究。核心风险是把结构变化误当暂时偏离；没有经济关系和稳定性检验，仅凭“跌多了会涨”不构成可靠策略。',
    highlights: ['中枢也可能已经改变'],
    related: ['arbitrage', 'random_walk', 'volatility'],
  },
  {
    id: 'financial_statement_analysis',
    title: '财务报表分析',
    aliases: ['报表分析', 'Financial Statement Analysis'],
    category: '估值',
    short: '结合三大报表、附注和业务信息判断经营与财务质量。',
    plain: '报表分析不是只算几个比率，而是核对利润、资产和现金能否互相解释。',
    detail: '通常从趋势、结构、同业和勾稽关系入手，分析盈利能力、偿债能力、运营效率和现金流。会计政策、一次性项目、审计意见与业务周期都会影响结论。',
    highlights: ['互相解释'],
    related: ['balance_sheet', 'income_statement', 'cash_flow_statement'],
  },
  {
    id: 'balance_sheet',
    title: '资产负债表',
    aliases: ['Balance Sheet', '财务状况表'],
    category: '估值',
    short: '反映企业在某一时点资产、负债和权益状况的报表。',
    plain: '资产负债表像企业某天的财务快照，告诉你拥有什么、欠什么、净剩多少。',
    detail: '核心恒等式为资产=负债+所有者权益。分析时关注资产质量、债务期限、营运资本和表外承诺；它是时点数据，需要与前后期间及现金流结合。',
    highlights: ['某天的财务快照'],
    related: ['asset', 'liability', 'owners_equity'],
  },
  {
    id: 'income_statement',
    title: '利润表',
    aliases: ['损益表', 'Income Statement'],
    category: '估值',
    short: '反映企业一定期间收入、费用和利润形成过程的报表。',
    plain: '利润表像一段时间的经营录像，从收入一路扣到最终利润。',
    detail: '利润表展示营收、成本、期间费用、税费和净利润。分析重点是增长来源、利润率变化、非经常损益和会计估计，不能把利润直接等同于现金。',
    highlights: ['一段时间的经营录像'],
    related: ['accounting_income', 'expense', 'profit'],
  },
  {
    id: 'cash_flow_statement',
    title: '现金流量表',
    aliases: ['现金流表', 'Cash Flow Statement'],
    category: '估值',
    short: '反映一定期间经营、投资和筹资现金流入流出的报表。',
    plain: '现金流量表追踪钱实际从哪里来、到哪里去，用来核验账面利润。',
    detail: '经营现金流反映主营回款，投资现金流体现资产购置与处置，筹资现金流反映借款、还款和股东回报。三类现金流组合比单个正负号更有意义。',
    highlights: ['钱实际从哪里来、到哪里去'],
    related: ['operating_cash_flow', 'free_cash_flow', 'financial_statement_analysis'],
  },
  {
    id: 'dcf',
    title: '现金流折现',
    aliases: ['DCF', 'Discounted Cash Flow'],
    category: '估值',
    short: '把未来现金流按风险和时间价值折算为当前价值的估值方法。',
    plain: 'DCF先估未来能产生多少钱，再把远期的钱打折换算成今天值多少。',
    detail: '企业DCF常预测自由现金流、估计终值并用WACC折现。结果对增长率、利润率、折现率和终值假设高度敏感，应给出情景区间而非单一精确价格。',
    highlights: ['远期的钱打折'],
    related: ['free_cash_flow', 'wacc', 'terminal_value'],
  },
  {
    id: 'irr',
    title: '内部收益率',
    aliases: ['IRR', 'Internal Rate of Return'],
    category: '估值',
    short: '使项目全部现金流净现值恰好等于零的折现率。',
    plain: 'IRR可理解为项目自身隐含的年化回报门槛，但复杂现金流可能算出多个结果。',
    detail: 'IRR高于资金成本时项目通常更有吸引力。它可能隐含中间现金流按同一IRR再投资，也会在现金流多次变号时出现多解或无解，因此应与NPV结合。',
    highlights: ['项目自身隐含的年化回报'],
    related: ['npv', 'payback_period', 'wacc'],
  },
  {
    id: 'npv',
    title: '净现值',
    aliases: ['NPV', 'Net Present Value'],
    category: '估值',
    short: '未来现金流现值合计减去初始投资后的净价值。',
    plain: 'NPV大于零表示按给定折现率计算，项目创造的价值超过投入。',
    detail: 'NPV直接衡量项目增加的货币价值，理论上优先于只看回收快慢。折现率和现金流预测决定结果，互斥项目比较还需保持口径与资本约束一致。',
    highlights: ['创造的价值超过投入'],
    related: ['irr', 'dcf', 'time_value_money'],
  },
  {
    id: 'payback_period',
    title: '回收期',
    aliases: ['投资回收期', 'Payback Period'],
    category: '估值',
    short: '项目累计现金流收回初始投资所需的时间。',
    plain: '回收期回答多久回本，直观但看不到回本之后还能创造多少价值。',
    detail: '静态回收期忽略货币时间价值，折现回收期会先折现现金流。两者都偏好短期项目，并忽略截止点后的现金流，适合作为流动性补充指标而非唯一决策依据。',
    highlights: ['多久回本', '回本之后'],
    related: ['npv', 'irr', 'time_value_money'],
  },
  {
    id: 'wacc',
    title: '加权平均资本成本',
    aliases: ['WACC', 'Weighted Average Cost of Capital'],
    category: '估值',
    short: '按资本结构加权后的股权与债务资金综合成本。',
    plain: 'WACC是公司同时使用股东资金和借款时，整体需要跨过的回报门槛。',
    detail: 'WACC通常按市场价值权重合并股权成本与税后债务成本，常用于企业自由现金流折现。资本结构、Beta、无风险利率和信用利差变化都会改变它。',
    highlights: ['整体需要跨过的回报门槛'],
    related: ['capm', 'credit_spread', 'dcf'],
  },
  {
    id: 'terminal_value',
    title: '终值',
    aliases: ['Terminal Value', '永续价值'],
    category: '估值',
    short: '明确预测期结束后所有剩余现金流的估计价值。',
    plain: 'DCF不可能逐年预测到永远，终值把远期剩余价值一次归纳进来。',
    detail: '常见方法是永续增长法和退出倍数法。终值在DCF中占比常很高，对永续增长率、折现率或估值倍数极敏感，必须做敏感性分析并检查经济合理性。',
    highlights: ['远期剩余价值'],
    related: ['dcf', 'wacc', 'npv'],
  },
  {
    id: 'discount_rate',
    title: '折现率',
    aliases: ['Discount Rate', '贴现率'],
    category: '估值',
    short: '把未来现金流换算成现值时采用的必要回报率。',
    plain: '折现率越高，说明要求的回报或风险补偿越高，未来现金流今天就越不值钱。',
    detail: '折现率应匹配现金流的风险、币种和名义或实际口径。企业自由现金流常用WACC，股权现金流常用股权成本；折现率微小变化也可能显著改变长期估值。',
    highlights: ['未来现金流今天就越不值钱'],
    related: ['dcf', 'wacc', 'time_value_money'],
  },
  {
    id: 'yield_curve',
    title: '收益率曲线',
    aliases: ['Yield Curve', '利率期限结构'],
    category: '估值',
    short: '同类债券在不同期限上的到期收益率关系。',
    plain: '收益率曲线把短期到长期的借钱价格连起来，形状会反映政策和经济预期。',
    detail: '正常曲线通常向上，倒挂表示短端收益率高于长端，常与紧缩和增长担忧相关。曲线形状还受期限溢价、供需与信用差异影响，不能机械预测衰退。',
    highlights: ['短期到长期的借钱价格'],
    related: ['interest_rate', 'bond', 'business_cycle'],
  },
  {
    id: 'credit_spread',
    title: '信用利差',
    aliases: ['Credit Spread', '信用风险溢价'],
    category: '估值',
    short: '信用债收益率相对相近久期无风险基准的差额。',
    plain: '信用利差是市场为承担发行人违约和流动性风险要求的额外补偿。',
    detail: '利差扩大通常表示信用担忧或流动性压力上升，收窄则可能反映风险偏好改善。比较时要控制期限、条款和基准，利差并非纯粹的违约概率。',
    highlights: ['要求的额外补偿'],
    related: ['credit', 'bond', 'wacc'],
  },

  // —— 宏观 ——
  {
    id: 'business_cycle',
    title: '宏观经济周期',
    aliases: ['经济周期', 'Business Cycle'],
    category: '宏观',
    short: '经济活动在扩张、放缓、衰退和复苏之间的周期性波动。',
    plain: '经济不是匀速前进，不同阶段的增长、通胀、政策和资产表现会发生组合变化。',
    detail: '周期没有固定长度，也不会严格按教科书顺序运行。判断阶段需综合GDP、就业、通胀、PMI、信用和政策，而不是依赖单一指标；市场价格还常领先实体数据。',
    highlights: ['不会严格按教科书顺序运行'],
    related: ['gdp', 'pmi', 'monetary_policy'],
  },
  {
    id: 'gdp',
    title: 'GDP',
    aliases: ['国内生产总值', 'Gross Domestic Product'],
    category: '宏观',
    short: '一定时期内一国或地区生产的最终商品与服务市场价值。',
    plain: 'GDP衡量经济总盘子和增长速度，但不直接等于居民收入、幸福感或企业利润。',
    detail: '可按生产、收入或支出法核算，名义GDP含价格变化，实际GDP剔除价格因素。分析增长还要看人均、结构、质量和修订值。',
    highlights: ['不直接等于居民收入'],
    related: ['business_cycle', 'cpi', 'unemployment_rate'],
  },
  {
    id: 'cpi',
    title: 'CPI',
    aliases: ['居民消费价格指数', 'Consumer Price Index'],
    category: '宏观',
    short: '衡量居民消费篮子价格水平随时间变化的指数。',
    plain: 'CPI追踪普通消费篮子整体贵了多少，但与你个人感受到的涨价可能不同。',
    detail: 'CPI权重来自代表性消费结构，常看同比、环比及核心CPI。食品能源波动大，核心口径有助观察持续趋势；CPI不等于全部资产价格或企业投入成本。',
    highlights: ['与你个人感受到的涨价可能不同'],
    related: ['inflation', 'ppi', 'policy_rate'],
  },
  {
    id: 'ppi',
    title: 'PPI',
    aliases: ['生产者价格指数', 'Producer Price Index'],
    category: '宏观',
    short: '衡量工业生产者出厂价格变化的指数。',
    plain: 'PPI更靠近生产端，反映企业卖出工业品时的价格变化。',
    detail: 'PPI可观察上游原材料与工业品价格压力，可能向CPI传导，但传导速度和幅度受需求、竞争与利润率影响。同比还会受基数效应扰动。',
    highlights: ['更靠近生产端'],
    related: ['cpi', 'inflation', 'pmi'],
  },
  {
    id: 'pmi',
    title: 'PMI',
    aliases: ['采购经理指数', 'Purchasing Managers Index'],
    category: '宏观',
    short: '通过企业采购经理调查反映经营活动扩张或收缩的扩散指数。',
    plain: 'PMI高于50通常表示多数受访企业情况在改善，低于50表示收缩项更多。',
    detail: 'PMI是环比方向指标，不表示产出同比增长50%。制造业与非制造业口径不同，还应看新订单、生产、就业和价格分项及连续趋势。',
    highlights: ['高于50', '低于50'],
    related: ['business_cycle', 'gdp', 'ppi'],
  },
  {
    id: 'unemployment_rate',
    title: '失业率',
    aliases: ['Unemployment Rate', '调查失业率'],
    category: '宏观',
    short: '劳动力中没有工作、正在寻找并可就业者的比例。',
    plain: '失业率只统计劳动力中的失业者，退出劳动力市场的人可能不在分母里。',
    detail: '失业率通常滞后于经济变化，还会受劳动参与率、人口结构和统计口径影响。就业改善可支持消费，但过紧劳动力市场也可能增加工资与通胀压力。',
    highlights: ['退出劳动力市场的人可能不在分母里'],
    related: ['gdp', 'business_cycle', 'cpi'],
  },
  {
    id: 'trade_balance',
    title: '贸易差额',
    aliases: ['净出口', 'Trade Balance'],
    category: '宏观',
    short: '商品和服务出口额减去进口额的差值。',
    plain: '出口大于进口是顺差，反之是逆差，但顺差本身不等于经济一定更健康。',
    detail: '贸易差额受内外需求、汇率、能源价格和产业链分工影响，也是GDP支出法中的净出口部分。分析时要区分数量、价格与一次性因素。',
    highlights: ['顺差本身不等于经济一定更健康'],
    related: ['exchange_rate', 'gdp', 'fiscal_policy'],
  },
  {
    id: 'central_bank',
    title: '中央银行',
    aliases: ['央行', 'Central Bank'],
    category: '宏观',
    short: '负责货币政策、货币发行和金融稳定等公共职能的机构。',
    plain: '央行通过利率、流动性和监管工具影响金融条件，但不能直接决定所有市场价格。',
    detail: '不同央行法定目标可能包括价格稳定、充分就业与金融稳定。政策通过银行、债券、汇率和预期等渠道传导，效果存在时滞且受财政和经济结构影响。',
    highlights: ['不能直接决定所有市场价格'],
    related: ['monetary_policy', 'open_market_operations', 'policy_rate'],
  },
  {
    id: 'open_market_operations',
    title: '公开市场操作',
    aliases: ['OMO', 'Open Market Operations'],
    category: '宏观',
    short: '央行在市场开展证券或流动性工具交易以调节资金面的操作。',
    plain: '央行通过投放或回笼短期资金，让市场利率更接近政策目标。',
    detail: '常见工具包括回购、逆回购和央行票据等，具体制度因经济体而异。单次投放不等于长期宽松，应结合到期量、净投放和政策利率观察。',
    highlights: ['投放或回笼短期资金'],
    related: ['central_bank', 'policy_rate', 'reserve_requirement_ratio'],
  },
  {
    id: 'reserve_requirement_ratio',
    title: '存款准备金率',
    aliases: ['准备金率', 'RRR', 'Reserve Requirement Ratio'],
    category: '宏观',
    short: '银行需按存款等负债的一定比例持有准备金的要求。',
    plain: '准备金率越高，银行可自由用于贷款和投资的资金空间通常越小。',
    detail: '调整准备金率会影响银行体系长期流动性和信用扩张能力，但实际贷款还取决于资本、需求、风险偏好与监管。降准不等于资金必然进入股市。',
    highlights: ['贷款和投资的资金空间'],
    related: ['central_bank', 'credit', 'money_supply'],
  },
  {
    id: 'rediscount_rate',
    title: '再贴现率',
    aliases: ['Rediscount Rate', '央行再贴现率'],
    category: '宏观',
    short: '商业银行持票据向央行融资时适用的利率。',
    plain: '银行把合格票据交给央行换取资金，再贴现率就是这类融资的价格。',
    detail: '再贴现率是传统货币政策工具之一，可影响银行融资成本和信贷意愿。现代政策框架中其重要性因国家和时期而异，不能与所有折现率概念混为一谈。',
    highlights: ['这类融资的价格'],
    related: ['central_bank', 'policy_rate', 'interest_rate'],
  },
  {
    id: 'policy_rate',
    title: '基准利率',
    aliases: ['政策利率', 'Policy Rate', 'Benchmark Rate'],
    category: '宏观',
    short: '央行用于表达和传导货币政策立场的关键利率。',
    plain: '政策利率像金融体系的参考锚，会逐步影响贷款、债券、汇率和估值。',
    detail: '不同国家可能使用回购利率、央行贷款利率或目标区间作为政策锚。政策利率并不等于所有人的实际借款利率，信用、期限和银行定价会形成差异。',
    highlights: ['金融体系的参考锚'],
    related: ['interest_rate', 'central_bank', 'open_market_operations'],
  },
  {
    id: 'monetary_policy',
    title: '货币政策',
    aliases: ['Monetary Policy', '宽松货币政策', '紧缩货币政策'],
    category: '宏观',
    short: '央行为实现价格、增长或就业目标而调节利率与流动性的政策。',
    plain: '货币政策主要改变钱的价格和金融条件，传导到实体经济通常需要时间。',
    detail: '宽松政策通常降低融资成本、增加流动性，紧缩政策则相反。政策效果取决于信用需求、银行传导和预期，市场还可能提前交易未来路径。',
    highlights: ['传导到实体经济通常需要时间'],
    related: ['central_bank', 'policy_rate', 'money_supply'],
  },
  {
    id: 'fiscal_policy',
    title: '财政政策',
    aliases: ['Fiscal Policy', '扩张性财政政策'],
    category: '宏观',
    short: '政府通过支出、税收和举债影响总需求与资源配置的政策。',
    plain: '财政政策直接改变政府花多少钱、向谁收税以及如何融资。',
    detail: '扩张性财政可托底需求，紧缩性财政可控制赤字和债务。效果受乘数、挤出效应、项目效率与执行时滞影响，应与货币政策和债务可持续性一起看。',
    highlights: ['政府花多少钱', '向谁收税'],
    related: ['monetary_policy', 'gdp', 'trade_balance'],
  },
  {
    id: 'stagflation',
    title: '滞胀',
    aliases: ['Stagflation', '停滞性通胀'],
    category: '宏观',
    short: '经济增长疲弱甚至停滞与高通胀同时出现。',
    plain: '滞胀最棘手之处是压通胀可能进一步伤增长，刺激增长又可能推高物价。',
    detail: '滞胀可能由供给冲击、政策失衡或结构性约束引发。判断需同时观察实际增长、就业和持续通胀，单月价格上涨或短期放缓都不足以下结论。',
    highlights: ['压通胀可能进一步伤增长'],
    related: ['inflation', 'business_cycle', 'monetary_policy'],
  },

  // —— 行为 ——
  {
    id: 'behavioral_finance',
    title: '行为金融学',
    aliases: ['Behavioral Finance', '行为金融'],
    category: '行为',
    short: '研究心理偏差和社会互动如何影响金融决策与市场价格。',
    plain: '投资者不是永远理性，情绪、经验和群体压力会系统性改变判断。',
    detail: '行为金融并不意味着传统定价理论无效，而是补充有限理性、有限套利和偏差持续存在的机制。识别偏差也不等于能稳定利用它获利。',
    highlights: ['不是永远理性'],
    related: ['anchoring_bias', 'loss_aversion', 'efficient_market_hypothesis'],
  },
  {
    id: 'anchoring_bias',
    title: '锚定效应',
    aliases: ['Anchoring Bias', '锚定偏差'],
    category: '行为',
    short: '判断过度依赖最先接触或印象深刻的参考信息。',
    plain: '把买入价、历史高点或某个目标价当成锚，可能妨碍依据新信息重新估值。',
    detail: '锚点即使与当前价值无关，也会影响预期和交易决策。应在信息更新后重新建立假设、估值区间和退出条件，而不是围绕旧价格找理由。',
    highlights: ['买入价', '当成锚'],
    related: ['confirmation_bias', 'loss_aversion', 'dcf'],
  },
  {
    id: 'overconfidence_bias',
    title: '过度自信',
    aliases: ['Overconfidence Bias', '过度自信偏差'],
    category: '行为',
    short: '高估自身知识、预测精度或控制结果能力的倾向。',
    plain: '过度自信常让人仓位过大、交易过多，并低估坏情景发生的概率。',
    detail: '盈利后容易把运气归因于能力，亏损时又归因于外部。用交易日志、基准比较、概率区间和事前止损规则，可减少结果偏差带来的自我强化。',
    highlights: ['仓位过大', '交易过多'],
    related: ['confirmation_bias', 'max_drawdown', 'position_ratio'],
  },
  {
    id: 'loss_aversion',
    title: '损失厌恶',
    aliases: ['Loss Aversion', '损失规避'],
    category: '行为',
    short: '同等金额损失带来的痛苦通常强于收益带来的快乐。',
    plain: '人们往往为了不确认亏损而死扛，也可能为了锁定小盈利而过早卖出。',
    detail: '损失厌恶会造成不对称风险偏好，并与处置效应相关。改进方法是事前定义仓位、退出条件和组合目标，用统一规则评估盈利与亏损头寸。',
    highlights: ['死扛', '过早卖出'],
    related: ['disposition_effect', 'stop_loss', 'anchoring_bias'],
  },
  {
    id: 'herding_effect',
    title: '羊群效应',
    aliases: ['从众效应', 'Herding Effect'],
    category: '行为',
    short: '个体跟随多数人行动，而弱化独立信息判断的现象。',
    plain: '看到大家都在买就觉得更安全，可能把“人多”误当成“判断正确”。',
    detail: '信息不充分、职业考核和社交压力都会强化羊群行为。跟随有时是理性学习，但拥挤交易会放大价格偏离、流动性踩踏和反转风险。',
    highlights: ['人多', '判断正确'],
    related: ['emotion_cycle', 'market_liquidity', 'behavioral_finance'],
  },
  {
    id: 'confirmation_bias',
    title: '确认偏误',
    aliases: ['Confirmation Bias', '证实偏差'],
    category: '行为',
    short: '更愿意寻找、相信支持既有观点的信息。',
    plain: '买入后只看利好、忽略反例，会让研究逐渐变成替原判断辩护。',
    detail: '确认偏误会影响信息搜索、解释和记忆。可通过写下可证伪条件、主动寻找反方证据、区分事实与观点来降低影响。',
    highlights: ['只看利好', '忽略反例'],
    related: ['overconfidence_bias', 'anchoring_bias', 'financial_statement_analysis'],
  },
  {
    id: 'disposition_effect',
    title: '处置效应',
    aliases: ['Disposition Effect', '处置偏差'],
    category: '行为',
    short: '倾向过早卖出盈利资产、过久持有亏损资产。',
    plain: '小赚就急着落袋，亏损却一直等回本，买入价因此支配了本应面向未来的决定。',
    detail: '处置效应与损失厌恶、锚定和心理账户相关。应比较从当前开始的预期收益风险，而不是用是否回到成本价决定持有。',
    highlights: ['小赚就急着落袋', '一直等回本'],
    related: ['loss_aversion', 'anchoring_bias', 'expectancy'],
  },

  // —— 公司金融 ——
  {
    id: 'corporate_governance',
    title: '公司治理',
    aliases: ['Corporate Governance', '治理结构'],
    category: '公司金融',
    short: '协调股东、董事会、管理层及其他利益相关者权责的制度安排。',
    plain: '公司治理解决“谁做决定、谁监督、出了问题谁负责”。',
    detail: '治理质量体现在董事会独立性、信息披露、关联交易、控制权制衡和中小股东保护等方面。形式合规不等于有效治理，还要观察长期资本配置和实际行为。',
    highlights: ['谁做决定', '谁监督'],
    related: ['equity_incentive', 'audit_opinion', 'share_pledge'],
  },
  {
    id: 'equity_incentive',
    title: '股权激励',
    aliases: ['Equity Incentive', '股票期权激励', '限制性股票激励'],
    category: '公司金融',
    short: '用股票、期权或与股价相关权益绑定员工与股东长期利益。',
    plain: '股权激励让管理层分享公司增值，但考核太松也可能变成低价福利。',
    detail: '评价方案要看授予价格、解锁条件、业绩口径、期限、稀释比例和离职安排。激励能缓解代理问题，也可能诱发短期业绩管理或过度冒险。',
    highlights: ['考核太松', '低价福利'],
    related: ['corporate_governance', 'owners_equity', 'eps'],
  },
  {
    id: 'mergers_acquisitions',
    title: '并购',
    aliases: ['兼并收购', 'M&A', 'Mergers and Acquisitions'],
    category: '公司金融',
    short: '通过合并、收购股权或资产取得企业控制权或业务资源。',
    plain: '并购可以快速获得市场和能力，但买得太贵或整合失败会毁掉价值。',
    detail: '并购价值来自协同、规模、技术或市场进入，也可能源于管理层扩张冲动。分析要看交易价格、支付方式、融资、业绩承诺、商誉和整合能力。',
    highlights: ['买得太贵', '整合失败'],
    related: ['goodwill', 'leveraged_buyout', 'corporate_governance'],
  },
  {
    id: 'leveraged_buyout',
    title: '杠杆收购',
    aliases: ['LBO', 'Leveraged Buyout'],
    category: '公司金融',
    short: '主要使用债务融资完成收购，并以被收购企业现金流偿债。',
    plain: 'LBO用较少股权撬动大额收购，回报可能放大，偿债压力也同步放大。',
    detail: '成功依赖稳定现金流、合理买入价、融资条件和退出价值。高杠杆会减少经营缓冲，利率上升或业绩不达预期时可能迅速触发违约和重组。',
    highlights: ['回报可能放大', '偿债压力也同步放大'],
    related: ['leverage', 'mergers_acquisitions', 'bankruptcy_reorganization'],
  },
  {
    id: 'bankruptcy_reorganization',
    title: '破产重整',
    aliases: ['破产重组', 'Bankruptcy Reorganization'],
    category: '公司金融',
    short: '在司法程序下调整债务和经营安排，争取恢复持续经营。',
    plain: '重整不是简单清算，而是债权人、股东和投资人重新分配损失与未来权益。',
    detail: '方案可能包括延期、减债、债转股、引入投资人和出售资产。原股东常面临大幅稀释，重整成功也不保证经营恢复；应以法院文件和正式披露为准。',
    highlights: ['重新分配损失与未来权益'],
    related: ['liability', 'leveraged_buyout', 'corporate_governance'],
  },
  {
    id: 'goodwill',
    title: '商誉',
    aliases: ['Goodwill', '并购商誉'],
    category: '公司金融',
    short: '企业合并成本超过可辨认净资产公允价值份额形成的资产。',
    plain: '商誉常代表收购时为品牌、客户和协同多付的钱，本身不能单独出售。',
    detail: '商誉通常不摊销但需进行减值测试。被收购业务不达预期可能产生大额减值，影响利润却不直接形成当期现金流出；高商誉需结合收购质量分析。',
    highlights: ['收购时', '多付的钱'],
    related: ['mergers_acquisitions', 'asset', 'net_profit'],
  },
  {
    id: 'share_buyback',
    title: '股份回购',
    aliases: ['股票回购', '回购', 'Share Buyback'],
    category: '公司金融',
    short: '公司使用资金从市场或股东手中购回自身股份。',
    plain: '回购可减少流通股份或用于激励，但只有买价合理、资金充足时才可能创造价值。',
    detail: '回购可能提升每股指标、传递估值信号或服务股权激励，也会消耗现金并改变杠杆。公告额度不等于实际完成量，应跟踪进度、价格和股份用途。',
    highlights: ['买价合理', '资金充足'],
    related: ['owners_equity', 'equity_incentive', 'free_cash_flow'],
  },
  {
    id: 'audit_opinion',
    title: '审计意见',
    aliases: ['审计报告意见', 'Audit Opinion'],
    category: '公司金融',
    short: '注册会计师对财务报表是否按适用准则公允反映所发表的意见。',
    plain: '标准无保留意见不是公司绝对没问题；非标准意见则提示报表范围或可靠性存在重要事项。',
    detail: '常见有无保留、保留、否定和无法表示意见，另有强调事项段。审计提供合理保证而非绝对保证，投资者还应阅读关键审计事项与内控报告。',
    highlights: ['不是公司绝对没问题', '重要事项'],
    related: ['financial_report', 'financial_statement_analysis', 'corporate_governance'],
  },

  // —— 风险管理补充 ——
  {
    id: 'stress_testing',
    title: '压力测试',
    aliases: ['Stress Testing', '情景压力测试'],
    category: '风险',
    short: '设定极端但合理的情景，评估组合或机构能否承受损失。',
    plain: '压力测试不问“平时大概亏多少”，而问“真遇到坏行情会不会扛不住”。',
    detail: '情景可来自历史危机或假设冲击，并联动价格、利率、汇率、信用和流动性。结果取决于情景设计，不能覆盖所有未知风险，应与VaR和应急预案配合。',
    highlights: ['真遇到坏行情会不会扛不住'],
    related: ['var95', 'cvar', 'monte_carlo_simulation'],
  },
  {
    id: 'monte_carlo_simulation',
    title: '蒙特卡洛模拟',
    aliases: ['Monte Carlo', 'Monte Carlo Simulation'],
    category: '风险',
    short: '按设定的随机模型反复抽样，估计结果分布与风险。',
    plain: '让模型随机跑很多遍，观察可能结果有多分散、坏结果出现多频繁。',
    detail: '模拟可用于定价、VaR、退休规划和项目风险。输出不会比输入假设更可靠，收益分布、相关性和参数若设错，再多次数也只会得到更稳定的错误答案。',
    highlights: ['随机跑很多遍', '不会比输入假设更可靠'],
    related: ['var95', 'stress_testing', 'correlation'],
  },
  {
    id: 'hedging',
    title: '对冲',
    aliases: ['Hedging', '套期保值'],
    category: '风险',
    short: '建立反向或相关头寸，降低特定风险敞口。',
    plain: '对冲像给已有风险加保护，通常会牺牲部分收益或付出持续成本。',
    detail: '可用期货、期权、互换或相关资产对冲价格、利率和汇率风险。对冲很少完美，仍有基差、期限、成本和交易对手风险；先明确要对冲哪一种风险。',
    highlights: ['牺牲部分收益', '持续成本'],
    related: ['derivative', 'insurance', 'delta'],
  },
  {
    id: 'insurance',
    title: '保险',
    aliases: ['Insurance', '风险转移'],
    category: '风险',
    short: '通过支付保费把约定损失风险转移给保险人的安排。',
    plain: '保险用确定的小额保费，换取不确定大额损失发生时的补偿。',
    detail: '保险依靠风险池、定价、核保和准备金运作，合同只覆盖约定责任并设有免赔、限额和除外条款。保险降低财务冲击，但不会消除事故本身。',
    highlights: ['确定的小额保费', '不确定大额损失'],
    related: ['hedging', 'put_option', 'position_ratio'],
  },
  {
    id: 'diversification',
    title: '分散化',
    aliases: ['分散投资', 'Diversification'],
    category: '风险',
    short: '组合相关性不完全相同的资产以降低个别风险。',
    plain: '持有更多名字不一定更分散，关键是风险来源不要都挤在同一个方向。',
    detail: '分散化主要降低非系统性风险，无法消除全市场共同下跌。压力时期相关性还可能上升，因此要看行业、因子、地区和流动性等真实暴露。',
    highlights: ['更多名字不一定更分散'],
    related: ['correlation', 'systematic_risk', 'unsystematic_risk'],
  },
  {
    id: 'systematic_risk',
    title: '系统性风险',
    aliases: ['市场风险', 'Systematic Risk'],
    category: '风险',
    short: '由宏观或市场共同因素引起、难以通过分散化消除的风险。',
    plain: '大盘、利率或经济冲击会同时影响很多资产，单纯多买几只股票躲不开。',
    detail: 'Beta常用于衡量相对市场的系统性风险暴露。降低这类风险通常要减少总敞口、跨资产配置或使用对冲，而不是只增加同市场持仓数量。',
    highlights: ['多买几只股票躲不开'],
    related: ['beta', 'capm', 'diversification'],
  },
  {
    id: 'unsystematic_risk',
    title: '非系统性风险',
    aliases: ['特质风险', '公司特有风险', 'Unsystematic Risk'],
    category: '风险',
    short: '由单个公司或局部事件引起、可通过分散化降低的风险。',
    plain: '产品失败、管理层问题等只影响少数标的，多样化持仓能减少单点冲击。',
    detail: '非系统性风险包括经营、治理和个别信用事件等。充分分散能降低但不能保证完全消除，过度分散还会增加成本并稀释研究优势。',
    highlights: ['减少单点冲击'],
    related: ['diversification', 'systematic_risk', 'corporate_governance'],
  },
]
