/**
 * Apex 全局指标/名词百科词条。
 * 新增词条只需追加本文件；页面用 <TermTip term="id"> 或打开「名词」面板搜索。
 */
export const GLOSSARY_CATEGORIES = ['绩效', '风险', '技术', '基本面', '策略', '行情']

/** @type {Array<{id:string,title:string,aliases:string[],category:string,short:string,detail:string,tip?:string}>} */
export const GLOSSARY_TERMS = [
  // —— 绩效 ——
  {
    id: 'total_return',
    title: '累计收益',
    aliases: ['总收益', '收益率'],
    category: '绩效',
    short: '相对初始资金，账户净值累计涨跌幅。',
    detail: '公式大致为（当前总资产 − 初始资金）/ 初始资金。正值赚钱，负值亏钱。看趋势时配合最大回撤一起看，避免只看收益忽略波动。',
  },
  {
    id: 'win_rate',
    title: '胜率',
    aliases: ['赢率', 'hit rate'],
    category: '绩效',
    short: '盈利笔数占已平仓交易的比例。',
    detail: '高胜率不等于赚钱：若赚时赚少、亏时亏多，仍可能总体亏损。需结合盈亏比、期望/笔一起看。',
    tip: '常见舒适区约 40%～60%，取决于策略风格。',
  },
  {
    id: 'expectancy',
    title: '期望/笔',
    aliases: ['期望值', '单笔期望'],
    category: '绩效',
    short: '平均每笔交易预期赚（或亏）多少钱。',
    detail: '综合胜率与盈亏幅度后的“单笔数学期望”。长期为正，策略才有统计优势；为负说明越做越亏。',
  },
  {
    id: 'profit_factor',
    title: '盈亏因子',
    aliases: ['Profit Factor', '利润因子'],
    category: '绩效',
    short: '总盈利金额 ÷ 总亏损金额（绝对值）。',
    detail: '>1 表示赚的比亏的多；=1 打平；<1 总体亏。比单独看胜率更能反映赚钱能力。',
    tip: '一般希望明显大于 1（如 1.3+），样本太少时数字不稳定。',
  },
  {
    id: 'payoff_ratio',
    title: '盈亏比',
    aliases: ['赔率', '平均盈亏比'],
    category: '绩效',
    short: '平均单笔盈利 ÷ 平均单笔亏损。',
    detail: '衡量“赚的时候赚多大、亏的时候亏多大”。高盈亏比策略即使胜率不高也可能盈利。',
  },
  {
    id: 'paper_turnover',
    title: '纸面换手率',
    aliases: ['换手率', 'turnover'],
    category: '绩效',
    short: '本系统模拟盘：累计成交额相对初始资金的比例。',
    detail: '注意：看板「换手率」是账户交易活跃度（成交额/初始资金），不是个股日线里的「成交量/流通股本」。个股换手见「换手率(个股)」。',
    tip: '换手过高通常意味着交易成本更高、更难跟上。',
  },
  {
    id: 'sharpe',
    title: '夏普比率',
    aliases: ['Sharpe', '夏普', 'rollingSharpe'],
    category: '绩效',
    short: '单位波动换来多少超额收益，衡量“性价比”。',
    detail: '用收益相对波动（标准差）标准化。同样收益，波动越小夏普越高。「20日」为近20个交易日滚动值，更敏感、更短视。',
    tip: '长期年化夏普 >1 较好；短窗口波动大，勿过度解读单日数字。',
  },
  {
    id: 'sortino',
    title: 'Sortino 比率',
    aliases: ['索提诺', 'Sortino'],
    category: '绩效',
    short: '类似夏普，但只惩罚下行波动。',
    detail: '上涨波动通常可接受，Sortino 主要看“亏的时候晃得多厉害”。对厌恶回撤的策略更贴切。',
  },
  {
    id: 'calmar',
    title: 'Calmar 比率',
    aliases: ['卡玛', 'Calmar'],
    category: '绩效',
    short: '年化收益 ÷ 最大回撤。',
    detail: '强调“扛住最惨回撤后还能赚多少”。回撤很深时 Calmar 会明显变差。',
  },
  {
    id: 'omega',
    title: 'Omega 比率',
    aliases: ['Omega'],
    category: '绩效',
    short: '收益分布中“好于门槛”与“差于门槛”的比重。',
    detail: '比均值/方差更关注整段收益分布形态。>1 表示超过阈值的部分更占优。',
  },
  {
    id: 'alpha',
    title: 'Alpha',
    aliases: ['超额收益', '阿尔法'],
    category: '绩效',
    short: '相对基准（如沪深300）多赚的部分。',
    detail: '正 Alpha 表示跑赢基准；负 Alpha 表示跑输。滚动 Alpha 看近期是否仍有超额。',
  },
  {
    id: 'beta',
    title: 'Beta',
    aliases: ['贝塔'],
    category: '绩效',
    short: '组合相对基准的敏感度。',
    detail: 'Beta≈1 大致跟涨跟跌；>1 波动放大；<1 更稳健；负值可能对冲。高 Beta 牛市赚更多、熊市也可能亏更多。',
  },
  {
    id: 'information_ratio',
    title: '信息比率 IR',
    aliases: ['IR', 'Information Ratio'],
    category: '绩效',
    short: '超额收益 ÷ 跟踪误差，衡量跑赢是否稳定。',
    detail: 'Alpha 高但忽上忽下时 IR 不高。希望稳定跑赢基准时重点看 IR。',
  },
  {
    id: 'tracking_error',
    title: '跟踪误差 TE',
    aliases: ['TE', 'Tracking Error'],
    category: '绩效',
    short: '组合收益与基准收益之差的波动。',
    detail: 'TE 大说明走势与基准偏离大（主动程度高）；指数增强策略通常希望 TE 可控。',
  },
  {
    id: 'unrealized_pnl',
    title: '未实现盈亏',
    aliases: ['浮盈', '浮亏'],
    category: '绩效',
    short: '当前持仓按市价估算、尚未卖出锁定的盈亏。',
    detail: '价格波动会变；只有平仓后才计入已实现盈亏。',
  },
  {
    id: 'realized_pnl',
    title: '已实现盈亏',
    aliases: ['落袋盈亏'],
    category: '绩效',
    short: '已经买卖平仓锁定的盈亏。',
    detail: '相对未实现更“实”。评估策略时两者要分开看。',
  },

  // —— 风险 ——
  {
    id: 'max_drawdown',
    title: '最大回撤',
    aliases: ['MDD', '回撤', 'Max Drawdown'],
    category: '风险',
    short: '净值从高点到低点的最大跌幅。',
    detail: '回答“历史上最惨亏过多少”。10% 回撤需要约 11% 涨幅才能回本；30% 回撤需要约 43%。风控核心指标之一。',
    tip: '回撤曲线越浅、恢复越快通常越好。',
  },
  {
    id: 'underwater_ratio',
    title: '水下占比',
    aliases: ['水下时间'],
    category: '风险',
    short: '净值处于历史高点之下的时间占比。',
    detail: '即使最大回撤不大，若长期“泡在水下”体验也很差。衡量煎熬时间。',
  },
  {
    id: 'drawdown_recovery',
    title: '回撤天数',
    aliases: ['回撤恢复天数'],
    category: '风险',
    short: '从回撤谷底爬回前高大致花了多少交易日。',
    detail: '恢复越慢，资金占用与心理压力越大。',
  },
  {
    id: 'var95',
    title: 'VaR95',
    aliases: ['VaR', '在险价值'],
    category: '风险',
    short: '在 95% 置信下，单日可能亏损的大致上限估计。',
    detail: '例如 VaR95=2% 可理解为：大约 20 个交易日里有 1 天，亏损可能达到或超过 2%（历史统计意义，非保证）。',
    tip: '极端行情会突破 VaR，需配合 CVaR、压力测试。',
  },
  {
    id: 'cvar',
    title: 'CVaR',
    aliases: ['ES', '条件在险价值', 'Expected Shortfall'],
    category: '风险',
    short: '一旦跌破 VaR，平均还会亏多少（尾部更狠）。',
    detail: '比 VaR 更关注“最坏那一截”的平均损失，风控上通常更保守。',
  },
  {
    id: 'ulcer',
    title: 'Ulcer Index',
    aliases: ['溃疡指数', 'Ulcer'],
    category: '风险',
    short: '衡量回撤深度与持续时间带来的“溃疡感”。',
    detail: '对长时间、反复回撤更敏感。数值越低，持有体验通常越好。',
  },
  {
    id: 'position_ratio',
    title: '仓位',
    aliases: ['仓位比例', 'position'],
    category: '风险',
    short: '股票市值占账户总资产的比例。',
    detail: '100% 满仓；50% 半仓。仓位越高，涨跌对净值影响越大。',
  },
  {
    id: 'max_losing_days',
    title: '最长连亏天',
    aliases: ['连亏'],
    category: '风险',
    short: '净值连续下跌的最长天数。',
    detail: '刻画短期连衰压力；与连胜/连亏笔数不同，这里偏账户日度净值。',
  },

  // —— 技术 ——
  {
    id: 'ma',
    title: '均线 MA',
    aliases: ['MA5', 'MA10', 'MA20', 'MA60', '移动平均'],
    category: '技术',
    short: '过去 N 根 K 线收盘价的平均值，平滑价格噪音。',
    detail: '短均线更灵敏，长均线更稳。价格在均线上方常被解读为偏多，下方偏空；金叉/死叉指短均线穿越长均线。',
  },
  {
    id: 'macd',
    title: 'MACD',
    aliases: ['DIF', 'DEA', '柱状图'],
    category: '技术',
    short: '用快慢指数均线差衡量趋势与动能。',
    detail: 'DIF 为快线，DEA 为信号线。DIF 上穿 DEA 为金叉（偏多），下穿为死叉（偏空）。柱线反映两者距离。',
  },
  {
    id: 'kdj',
    title: 'KDJ',
    aliases: ['随机指标', 'K值', 'D值', 'J值'],
    category: '技术',
    short: '反映收盘价在近期高低区间中的相对位置。',
    detail: '常用 9,3,3。K、D 在低位金叉偏超卖反弹；高位死叉偏超买回落。J 更敏感、噪声也更大。参考线常见 20/50/80。',
  },
  {
    id: 'rsi',
    title: 'RSI',
    aliases: ['相对强弱', 'RSI6', 'RSI12', 'RSI14', 'RSI24'],
    category: '技术',
    short: '用一段时间内涨跌幅对比，衡量超买超卖与动能强弱。',
    detail: '常见周期 6/12/14/24。数值多在 0～100：偏高（如>70）偏超买，偏低（如<30）偏超卖。本系统 S2 策略常用 RSI 回调买点思路：趋势尚可时等 RSI 回落再介入，而非追高。',
    tip: '单看 RSI 钝化很常见，最好结合均线/趋势位置。',
  },
  {
    id: 'atr',
    title: 'ATR',
    aliases: ['ATR14', '真实波幅', 'Average True Range'],
    category: '技术',
    short: '一段时间内的平均真实波幅，衡量波动大小（价格单位）。',
    detail: 'True Range 取「当日高低差、高点距昨收、低点距昨收」三者最大，再做 N 日平均（常用 14）。ATR 变大说明波动加剧。模拟盘「应用 ATR 止损」常用 ATR14 估算止损/止盈距离。',
  },
  {
    id: 'atr_pct',
    title: 'ATR%',
    aliases: ['ATR百分比', 'atrPct', '相对波幅'],
    category: '技术',
    short: 'ATR ÷ 现价 × 100%，把波动换成百分比，方便跨股票比较。',
    detail: '高价股与低价股的 ATR 绝对值不好比，用 ATR% 更直观。选股里「ATR%≤」用于过滤波动过大、难拿得住的标的；过低也可能流动性/弹性不足。',
    tip: '短线常看 ATR% 适中；过高更适合减小仓位或放宽止损。',
  },
  {
    id: 'rs20',
    title: 'RS20',
    aliases: ['RS20 vs沪深300', '相对强度20', 'rs20VsHs300'],
    category: '技术',
    short: '近 20 日个股涨跌幅 − 近 20 日沪深300涨跌幅（百分点）。',
    detail: '正值表示近 20 日相对大盘更强，负值更弱。单位是百分点（pp），不是价格。用来找阶段强势股或避开明显跑输大盘的弱势股。',
    tip: 'RS 高=相对强，不保证继续涨；高位强势也可能分歧加大。',
  },
  {
    id: 'rs60',
    title: 'RS60',
    aliases: ['RS60 vs沪深300', '相对强度60', 'rs60VsHs300'],
    category: '技术',
    short: '近 60 日个股涨跌幅 − 近 60 日沪深300涨跌幅（百分点）。',
    detail: '比 RS20 更平滑，看中期相对强弱。RS20 与 RS60 同为正，常表示短中期都偏强；二者背离时要警惕趋势切换。',
  },
  {
    id: 'boll',
    title: '布林带',
    aliases: ['BOLL', 'Bollinger', '布林'],
    category: '技术',
    short: '中轨均线 ± 若干倍标准差，刻画价格波动通道。',
    detail: '价格贴近上轨偏强/可能超买，贴近下轨偏弱/可能超卖；带宽扩张=波动加大，收窄=波动收敛。常与突破、回归均值策略一起用。',
  },
  {
    id: 'up_days',
    title: '连涨天数',
    aliases: ['连涨', 'upDays'],
    category: '技术',
    short: '收盘价连续高于前一日的交易日数。',
    detail: '选股条件「连涨≥」用来找短线连续走强的票。连涨越长，追高风险往往越大，需结合量能与位置。',
  },
  {
    id: 'td9',
    title: '神奇九转',
    aliases: ['TD Sequential', '九转', 'TD9'],
    category: '技术',
    short: '统计连续高于/低于 4 日前收盘的计数，满 9 视为结构完成。',
    detail: '上涨九转（卖结构）与下跌九转（买结构）是计数提示，不是保证反转。建议结合趋势、位置与成交量，勿单独重仓。',
  },
  {
    id: 'volume_ratio',
    title: '量比',
    aliases: ['量比', 'volumeRatio'],
    category: '技术',
    short: '今日成交量相对近几日均量的倍数。',
    detail: '本系统选股/个股量比多为：当日量 ÷ 近 20 日日均量。>1 放量，<1 缩量。突然放大常伴随消息或资金异动，需结合涨跌方向解读。',
  },
  {
    id: 'stock_turnover',
    title: '换手率(个股)',
    aliases: ['个股换手', 'turnover_rate'],
    category: '技术',
    short: '当日成交量 ÷ 流通股本，衡量交易活跃度。',
    detail: '与纸面账户「换手率」不同。过高可能短线博弈激烈；过低可能流动性差。K 线悬浮「换」即此指标。',
  },
  {
    id: 'seal_amount',
    title: '封单金额',
    aliases: ['封单', '封板资金', 'sealAmount'],
    category: '技术',
    short: '涨停（或跌停）时挂在涨停价上的未成交委托金额。',
    detail: '封单越大，通常表示封板更牢、短线资金更集中；开板/炸板后封单会明显下降。涨停复盘卡片上的「封」即此。',
  },
  {
    id: 'lianban',
    title: '连板',
    aliases: ['连板高度', '几板', 'lianban'],
    category: '行情',
    short: '连续涨停的天数/高度，如 3 板=连续三个交易日涨停。',
    detail: '高度越高情绪越热，分歧与回撤风险也越大。复盘里「首板/2板/3板…」按连板高度分层。',
  },
  {
    id: 'promote_rate',
    title: '晋级率',
    aliases: ['晋级', '一进二', '二进三', 'promoteRate'],
    category: '行情',
    short: '昨日某高度涨停股中，今日成功走到更高连板的比例。',
    detail: '本系统常用口径：今日 N 板家数 ÷ 昨日 (N−1) 板家数。例如「四进五」看昨日 4 板晋级到今日 5 板的效率。晋级率高=接力情绪强；过低=高潮后分歧。',
  },

  // —— 基本面 ——
  {
    id: 'pe_ttm',
    title: '市盈率 PE',
    aliases: ['PE', 'PE_TTM', '市盈率'],
    category: '基本面',
    short: '股价 ÷ 每股收益，贵不贵的常见尺子。',
    detail: 'TTM 用近四个季度盈利。高 PE 可能透支增长预期，也可能因盈利暂时偏低。亏损公司 PE 无意义或为负。',
  },
  {
    id: 'pb',
    title: '市净率 PB',
    aliases: ['PB', '市净率'],
    category: '基本面',
    short: '股价 ÷ 每股净资产。',
    detail: '偏资产型公司（银行、地产等）更常看 PB。成长股 PB 往往偏高，需结合 ROE。',
  },
  {
    id: 'roe',
    title: 'ROE',
    aliases: ['净资产收益率', '股东回报'],
    category: '基本面',
    short: '净利润相对净资产的回报能力。',
    detail: '衡量公司用股东的钱赚得多不多。长期稳定且较高的 ROE 常被视作优质经营信号，但要防杠杆堆出来的假高。',
  },
  {
    id: 'circ_mv',
    title: '流通市值',
    aliases: ['市值', '流通盘'],
    category: '基本面',
    short: '可交易股份的总市值。',
    detail: '小市值波动更大、流动性可能更差；大市值相对稳健但弹性常更小。',
  },

  // —— 策略 ——
  {
    id: 'strategy_signal',
    title: '策略信号',
    aliases: ['信号', 'S1', 'S2', 'S3'],
    category: '策略',
    short: '策略对某标的给出的 BUY/SELL 等交易提示。',
    detail: '带评分与理由，是选股/决策的输入，不是下单指令。需结合仓位、风控与自己的判断。',
  },
  {
    id: 'confluence',
    title: '策略共振',
    aliases: ['共振', '多策略共振'],
    category: '策略',
    short: '同一标的、同一方向被多个策略同时点名。',
    detail: '共振越多，系统内一致性越强，但仍可能集体犯错。适合提高关注优先级，而非无限加仓。',
  },
  {
    id: 'hot_confluence',
    title: '热点共振',
    aliases: ['多平台热点', '热点'],
    category: '策略',
    short: '多个舆情/热度平台同时上榜的标的。',
    detail: '反映短期关注度，不等于基本面变好。常有高波动与情绪退潮风险。',
  },
  {
    id: 'forward_eval',
    title: '前瞻评估',
    aliases: ['前瞻收益', 'forward'],
    category: '策略',
    short: '用历史信号之后 N 日涨跌，回看信号是否“说对了”。',
    detail: '胜率、均收益是事后统计，有样本偏差，不能保证未来同样有效。用于粗检策略是否空转。',
  },
  {
    id: 'universe',
    title: '股票池',
    aliases: ['Universe', '候选池'],
    category: '策略',
    short: '策略运行时扫描的候选股票集合。',
    detail: '通常来自自选或筛选结果。池子质量直接影响信号质量。',
  },
  {
    id: 'backtest',
    title: '回测',
    aliases: ['历史回放'],
    category: '策略',
    short: '用历史行情模拟策略交易并统计绩效。',
    detail: '帮助理解逻辑与风险，但无法完全复现滑点、停牌、未来函数等问题。过拟合曲线好看不等于实盘能赚。',
  },
  {
    id: 'paper_trading',
    title: '模拟盘',
    aliases: ['纸面交易', 'paper'],
    category: '策略',
    short: '用虚拟资金按规则成交，验证流程与风控。',
    detail: '比回测更接近实操节奏，但仍无真实冲击成本与情绪。适合先跑通再考虑实盘。',
  },

  // —— 行情 ——
  {
    id: 'ohlc',
    title: '开高低收',
    aliases: ['OHLC', 'K线'],
    category: '行情',
    short: '一根 K 线的开盘、最高、最低、收盘价。',
    detail: '日/周/月 K 聚合方式不同：周/月开=首日开、收=末日收、高/低取区间极值。',
  },
  {
    id: 'pct_chg',
    title: '涨跌幅',
    aliases: ['涨幅', '跌幅'],
    category: '行情',
    short: '相对前收（或区间起点）的百分比变化。',
    detail: 'A 股常见涨跌停限制（主板约 ±10%，创业板/科创板约 ±20% 等，以交易规则为准）。',
  },
  {
    id: 'amount',
    title: '成交额',
    aliases: ['额', '成交金额'],
    category: '行情',
    short: '成交的金额总和（价格×数量汇总）。',
    detail: '比单纯看成交量更能反映资金参与程度。',
  },
  {
    id: 'qfq',
    title: '前复权',
    aliases: ['复权', 'qfq'],
    category: '行情',
    short: '把历史价格按除权除息调整，使走势可连续比较。',
    detail: '本系统日线多为前复权，适合看形态与均线；看绝对历史成交价时要注意与不复权的差异。',
  },
]
